import sys
fname = "small-genome.fasta" if len(sys.argv) < 2  else str(sys.argv[1])
plsz = 4 if len(sys.argv) < 3  else int(sys.argv[2])
#print ("File Name: %s" % fname)

x = open(fname,"r")
a = x.read()
# skip the first line from fasta file
b = a.split('\n',1)[1]
seq = b.replace("\n","")

#seq="ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATCTGTTCTCTAAACGAACTTTAAAATCTGTGTGGCTGTCACTCGGCTGCATGCTTAGTGCACTCACGCAGTATAATTAATAACTAATTACTGTCGTTGACAGGACACGAGTAACTCGTCTATCTTCTGCAGGCTGCTTACGGTTTCGTCCGTGTTGCAGCCGATCATCAGCACATCTAGGTTTCGTCCGGGTGTGACCGAAAGGTAAGATGGAGAGCCTTGTCCCTGGTTTCAACGAGAAAACACACGTCCAACTCAGTTTGCCTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGGAGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACATCTTAAAGATGGCACTTGTGGCTTAGTAGAAGTTGAAAAAGGCGTTTTGCCTCAACTTGAACAGCCCTATGTGTTCATCAAACGTTCGGATGCTCGAACTGCACCTCATGGTCATGTTATGGTTGAGCTGGTAGCAGAACTCGAAGGCATTCAGTACGGTCGTAGTGGTGAGACACTTGGTGTCCTTGTCCCTCATGTGGGCGAAATACCAGTGGCTTACCGCAAGGTTCTTCTTCGTAAGAACGGTAATAAAGGAGCTGGTGGCCATAGTTACGGCGCCGATCTAAAGTCATTTGACTTAGGCGACGAGCTTGGCACTGATCCTTATGAAGATTTTCAAGAAAACTGGAACACTAAACATAGCAGTGGTGTTACCCGTGAACTCATGCGTGAGCTTAACGGAGGGGCATACACTCGCTATGTCGATAACAACTTCTGTGGCCCTGATGGCTACCCTCTTGAGTGCATTAAAGACCTTCTAGCACGTGCTGGTAAAGCTTCATGCACTTTGTCCGAACAACTGGACTTTATTGACACTAAGAGGGGTGTATACTGCTGCCGTGAACATGAGCATGAAATTGCTTGGTACACGGAACGTTCTGAAAAGAGCTATGAATTGCA"
dict = {"A":"T", "T":"A", "C":"G", "G":"C"}

def getComp(seq):
  return "".join([dict[i] for i in seq[::-1]])

def isPal(seq):
  return seq == getComp(seq)

#print (getComp(seq))
#print(isPal("ACGT"))
#print(isPal("ACGTA"))

# pick every 4 characters at i, 
# i, to n , check every 4 for a pali

list = []
for i in range (0, len(seq)+1-plsz, 1):
                if (isPal(seq[i:i+plsz])):
                                list.append(i)

#print(list)
pct = (len(list)/len(seq))*100
#print("File,PalLength,SeqSz,PalCnt,PalPct")
print(fname, end=',')
print(plsz, end=',')
print(len(seq), end=',')
print(len(list), end=',')
print(pct)
